name: Deploy

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install node packages and build angular app
        uses: actions/angular-github-actions
      - name: Deploy to Google App Engine
        uses: atRobertoFlores/gae_deploy_action@master
        with:
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          project_name: ${{ secrets.GOOGLE_PROJECT_ID }}
