name: Deploy

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Angular Full CI
        uses: colbyhill21/angular-full-ci/@v1.0
      - name: Deploy to Google App Engine
        uses: atRobertoFlores/gae_deploy_action@master
        with:
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          project_name: ${{ secrets.GOOGLE_PROJECT_ID }}
