name: Deploy

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Initialize Google Cloud SDK
        uses: zxyle/publish-gae-action@v2.3
        with:
          service_account_email: secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL
          service_account_key: secrets.GOOGLE_SERVICE_ACCOUNT_KEY
          project_id: secrets.GOOGLE_PROJECT_ID
          gae_config_path: ./app.yaml
      - name: Publish app to Google App Engine
        run: |
          gcloud config set project ${{ secrets.GOOGLE_PROJECT_ID }}
          gcloud -q app deploy app.yaml --promote